# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pattern_recognition_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_pattern_recognition(object):
    def setupUi(self, form_pattern_recognition):
        form_pattern_recognition.setObjectName("form_pattern_recognition")
        form_pattern_recognition.resize(510, 660)
        form_pattern_recognition.setMinimumSize(QtCore.QSize(510, 660))
        form_pattern_recognition.setMaximumSize(QtCore.QSize(510, 660))
        self.le_amount_of_points = QtWidgets.QLineEdit(form_pattern_recognition)
        self.le_amount_of_points.setGeometry(QtCore.QRect(140, 17, 250, 21))
        self.le_amount_of_points.setReadOnly(False)
        self.le_amount_of_points.setObjectName("le_amount_of_points")
        self.lb_amount_of_points = QtWidgets.QLabel(form_pattern_recognition)
        self.lb_amount_of_points.setGeometry(QtCore.QRect(20, 20, 121, 16))
        self.lb_amount_of_points.setObjectName("lb_amount_of_points")
        self.le_amount_of_classes = QtWidgets.QLineEdit(form_pattern_recognition)
        self.le_amount_of_classes.setGeometry(QtCore.QRect(140, 47, 250, 21))
        self.le_amount_of_classes.setReadOnly(False)
        self.le_amount_of_classes.setObjectName("le_amount_of_classes")
        self.lb_amount_of_classes = QtWidgets.QLabel(form_pattern_recognition)
        self.lb_amount_of_classes.setGeometry(QtCore.QRect(20, 50, 121, 16))
        self.lb_amount_of_classes.setObjectName("lb_amount_of_classes")
        self.gv_canvas = QtWidgets.QGraphicsView(form_pattern_recognition)
        self.gv_canvas.setGeometry(QtCore.QRect(5, 80, 500, 500))
        self.gv_canvas.setObjectName("gv_canvas")
        self.pb_generate = QtWidgets.QPushButton(form_pattern_recognition)
        self.pb_generate.setGeometry(QtCore.QRect(200, 590, 110, 32))
        self.pb_generate.setObjectName("pb_generate")
        self.pb_start = QtWidgets.QPushButton(form_pattern_recognition)
        self.pb_start.setGeometry(QtCore.QRect(200, 625, 110, 32))
        self.pb_start.setObjectName("pb_start")

        self.retranslateUi(form_pattern_recognition)
        QtCore.QMetaObject.connectSlotsByName(form_pattern_recognition)

    def retranslateUi(self, form_pattern_recognition):
        _translate = QtCore.QCoreApplication.translate
        form_pattern_recognition.setWindowTitle(_translate("form_pattern_recognition", "Pattern recognition"))
        self.le_amount_of_points.setText(_translate("form_pattern_recognition", "10000"))
        self.le_amount_of_points.setPlaceholderText(_translate("form_pattern_recognition", "10000"))
        self.lb_amount_of_points.setText(_translate("form_pattern_recognition", "Amount of points:"))
        self.le_amount_of_classes.setText(_translate("form_pattern_recognition", "7"))
        self.le_amount_of_classes.setPlaceholderText(_translate("form_pattern_recognition", "7"))
        self.lb_amount_of_classes.setText(_translate("form_pattern_recognition", "Amount of classes:"))
        self.pb_generate.setText(_translate("form_pattern_recognition", "Generate"))
        self.pb_start.setText(_translate("form_pattern_recognition", "Start"))
