# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'neural_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_neuralink(object):
    def setupUi(self, form_neuralink):
        form_neuralink.setObjectName("form_neuralink")
        form_neuralink.resize(200, 260)
        form_neuralink.setMinimumSize(QtCore.QSize(200, 260))
        form_neuralink.setMaximumSize(QtCore.QSize(200, 260))
        form_neuralink.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pb_predict = QtWidgets.QPushButton(form_neuralink)
        self.pb_predict.setGeometry(QtCore.QRect(100, 220, 85, 32))
        self.pb_predict.setObjectName("pb_predict")
        self.lb_number = QtWidgets.QLabel(form_neuralink)
        self.lb_number.setGeometry(QtCore.QRect(20, 10, 71, 16))
        self.lb_number.setObjectName("lb_number")
        self.gv_digit = QtWidgets.QGraphicsView(form_neuralink)
        self.gv_digit.setGeometry(QtCore.QRect(10, 35, 180, 180))
        self.gv_digit.setObjectName("gv_digit")
        self.pb_train = QtWidgets.QPushButton(form_neuralink)
        self.pb_train.setGeometry(QtCore.QRect(15, 220, 85, 32))
        self.pb_train.setObjectName("pb_train")

        self.retranslateUi(form_neuralink)
        QtCore.QMetaObject.connectSlotsByName(form_neuralink)

    def retranslateUi(self, form_neuralink):
        _translate = QtCore.QCoreApplication.translate
        form_neuralink.setWindowTitle(_translate("form_neuralink", "Neuralink"))
        self.pb_predict.setText(_translate("form_neuralink", "Predict"))
        self.lb_number.setText(_translate("form_neuralink", "Write digit:"))
        self.pb_train.setText(_translate("form_neuralink", "Train"))
