# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'syntactic_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_syntactic(object):
    def setupUi(self, form_syntactic):
        form_syntactic.setObjectName("form_syntactic")
        form_syntactic.resize(820, 785)
        form_syntactic.setMinimumSize(QtCore.QSize(820, 785))
        form_syntactic.setMaximumSize(QtCore.QSize(890, 785))
        form_syntactic.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pb_recognize = QtWidgets.QPushButton(form_syntactic)
        self.pb_recognize.setGeometry(QtCore.QRect(300, 735, 110, 32))
        self.pb_recognize.setObjectName("pb_recognize")
        self.gb_input_data = QtWidgets.QGroupBox(form_syntactic)
        self.gb_input_data.setGeometry(QtCore.QRect(10, 0, 301, 71))
        self.gb_input_data.setObjectName("gb_input_data")
        self.lb_primitives = QtWidgets.QLabel(self.gb_input_data)
        self.lb_primitives.setGeometry(QtCore.QRect(10, 30, 111, 16))
        self.lb_primitives.setObjectName("lb_primitives")
        self.cb_primitives = QtWidgets.QComboBox(self.gb_input_data)
        self.cb_primitives.setGeometry(QtCore.QRect(120, 30, 170, 26))
        self.cb_primitives.setObjectName("cb_primitives")
        self.lb_chart = QtWidgets.QLabel(form_syntactic)
        self.lb_chart.setGeometry(QtCore.QRect(20, 90, 51, 16))
        self.lb_chart.setObjectName("lb_chart")
        self.gv_canvas = QtWidgets.QGraphicsView(form_syntactic)
        self.gv_canvas.setGeometry(QtCore.QRect(10, 120, 800, 600))
        self.gv_canvas.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gv_canvas.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gv_canvas.setObjectName("gv_canvas")
        self.pb_clear = QtWidgets.QPushButton(form_syntactic)
        self.pb_clear.setGeometry(QtCore.QRect(420, 735, 110, 32))
        self.pb_clear.setObjectName("pb_clear")

        self.retranslateUi(form_syntactic)
        QtCore.QMetaObject.connectSlotsByName(form_syntactic)

    def retranslateUi(self, form_syntactic):
        _translate = QtCore.QCoreApplication.translate
        form_syntactic.setWindowTitle(_translate("form_syntactic", "Syntactic method"))
        self.pb_recognize.setText(_translate("form_syntactic", "Recognize"))
        self.gb_input_data.setTitle(_translate("form_syntactic", "Input data:"))
        self.lb_primitives.setText(_translate("form_syntactic", "Set of primitives:"))
        self.lb_chart.setText(_translate("form_syntactic", "Art:"))
        self.pb_clear.setText(_translate("form_syntactic", "Clear"))
