# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maxmin_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_maxmin(object):
    def setupUi(self, form_maxmin):
        form_maxmin.setObjectName("form_maxmin")
        form_maxmin.resize(510, 700)
        form_maxmin.setMinimumSize(QtCore.QSize(510, 700))
        form_maxmin.setMaximumSize(QtCore.QSize(510, 700))
        self.le_amount_of_points = QtWidgets.QLineEdit(form_maxmin)
        self.le_amount_of_points.setGeometry(QtCore.QRect(140, 17, 250, 21))
        self.le_amount_of_points.setReadOnly(False)
        self.le_amount_of_points.setObjectName("le_amount_of_points")
        self.lb_amount_of_points = QtWidgets.QLabel(form_maxmin)
        self.lb_amount_of_points.setGeometry(QtCore.QRect(20, 20, 121, 16))
        self.lb_amount_of_points.setObjectName("lb_amount_of_points")
        self.gv_canvas = QtWidgets.QGraphicsView(form_maxmin)
        self.gv_canvas.setGeometry(QtCore.QRect(5, 80, 500, 500))
        self.gv_canvas.setObjectName("gv_canvas")
        self.pb_generate = QtWidgets.QPushButton(form_maxmin)
        self.pb_generate.setGeometry(QtCore.QRect(200, 590, 110, 32))
        self.pb_generate.setObjectName("pb_generate")
        self.pb_start = QtWidgets.QPushButton(form_maxmin)
        self.pb_start.setGeometry(QtCore.QRect(200, 625, 110, 32))
        self.pb_start.setObjectName("pb_start")
        self.pb_k_means = QtWidgets.QPushButton(form_maxmin)
        self.pb_k_means.setGeometry(QtCore.QRect(200, 660, 110, 32))
        self.pb_k_means.setObjectName("pb_k_means")

        self.retranslateUi(form_maxmin)
        QtCore.QMetaObject.connectSlotsByName(form_maxmin)

    def retranslateUi(self, form_maxmin):
        _translate = QtCore.QCoreApplication.translate
        form_maxmin.setWindowTitle(_translate("form_maxmin", "Maxmin"))
        self.le_amount_of_points.setText(_translate("form_maxmin", "10000"))
        self.le_amount_of_points.setPlaceholderText(_translate("form_maxmin", "10000"))
        self.lb_amount_of_points.setText(_translate("form_maxmin", "Number of points:"))
        self.pb_generate.setText(_translate("form_maxmin", "Generate"))
        self.pb_start.setText(_translate("form_maxmin", "Start"))
        self.pb_k_means.setText(_translate("form_maxmin", "K-means "))
