# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splitting_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_splitting(object):
    def setupUi(self, form_splitting):
        form_splitting.setObjectName("form_splitting")
        form_splitting.resize(700, 640)
        form_splitting.setMinimumSize(QtCore.QSize(700, 640))
        form_splitting.setMaximumSize(QtCore.QSize(700, 640))
        self.gv_canvas = QtWidgets.QGraphicsView(form_splitting)
        self.gv_canvas.setGeometry(QtCore.QRect(5, 90, 690, 500))
        self.gv_canvas.setObjectName("gv_canvas")
        self.pb_calculate = QtWidgets.QPushButton(form_splitting)
        self.pb_calculate.setGeometry(QtCore.QRect(295, 600, 110, 32))
        self.pb_calculate.setObjectName("pb_calculate")
        self.gb_input_data = QtWidgets.QGroupBox(form_splitting)
        self.gb_input_data.setGeometry(QtCore.QRect(10, 0, 150, 80))
        self.gb_input_data.setObjectName("gb_input_data")
        self.lb_p_c2 = QtWidgets.QLabel(self.gb_input_data)
        self.lb_p_c2.setGeometry(QtCore.QRect(10, 55, 41, 16))
        self.lb_p_c2.setObjectName("lb_p_c2")
        self.le_p_c1 = QtWidgets.QLineEdit(self.gb_input_data)
        self.le_p_c1.setGeometry(QtCore.QRect(60, 22, 71, 21))
        self.le_p_c1.setReadOnly(False)
        self.le_p_c1.setObjectName("le_p_c1")
        self.le_p_c2 = QtWidgets.QLineEdit(self.gb_input_data)
        self.le_p_c2.setGeometry(QtCore.QRect(60, 52, 71, 21))
        self.le_p_c2.setReadOnly(False)
        self.le_p_c2.setObjectName("le_p_c2")
        self.lb_p_c1 = QtWidgets.QLabel(self.gb_input_data)
        self.lb_p_c1.setGeometry(QtCore.QRect(10, 25, 41, 16))
        self.lb_p_c1.setObjectName("lb_p_c1")
        self.gb_output_data = QtWidgets.QGroupBox(form_splitting)
        self.gb_output_data.setGeometry(QtCore.QRect(170, 0, 521, 81))
        self.gb_output_data.setObjectName("gb_output_data")
        self.lb_false_alarm_probability = QtWidgets.QLabel(self.gb_output_data)
        self.lb_false_alarm_probability.setGeometry(QtCore.QRect(10, 25, 141, 16))
        self.lb_false_alarm_probability.setObjectName("lb_false_alarm_probability")
        self.le_false_alarm_probability = QtWidgets.QLineEdit(self.gb_output_data)
        self.le_false_alarm_probability.setGeometry(QtCore.QRect(160, 22, 121, 21))
        self.le_false_alarm_probability.setText("")
        self.le_false_alarm_probability.setReadOnly(True)
        self.le_false_alarm_probability.setPlaceholderText("")
        self.le_false_alarm_probability.setObjectName("le_false_alarm_probability")
        self.lb_missing_error_detection_probability = QtWidgets.QLabel(self.gb_output_data)
        self.lb_missing_error_detection_probability.setGeometry(QtCore.QRect(10, 55, 211, 16))
        self.lb_missing_error_detection_probability.setObjectName("lb_missing_error_detection_probability")
        self.le_missing_error_detection_probability = QtWidgets.QLineEdit(self.gb_output_data)
        self.le_missing_error_detection_probability.setGeometry(QtCore.QRect(230, 52, 121, 21))
        self.le_missing_error_detection_probability.setText("")
        self.le_missing_error_detection_probability.setReadOnly(True)
        self.le_missing_error_detection_probability.setPlaceholderText("")
        self.le_missing_error_detection_probability.setObjectName("le_missing_error_detection_probability")
        self.lb_total_error = QtWidgets.QLabel(self.gb_output_data)
        self.lb_total_error.setGeometry(QtCore.QRect(290, 25, 71, 16))
        self.lb_total_error.setObjectName("lb_total_error")
        self.le_total_error = QtWidgets.QLineEdit(self.gb_output_data)
        self.le_total_error.setGeometry(QtCore.QRect(370, 22, 141, 21))
        self.le_total_error.setText("")
        self.le_total_error.setReadOnly(True)
        self.le_total_error.setPlaceholderText("")
        self.le_total_error.setObjectName("le_total_error")

        self.retranslateUi(form_splitting)
        QtCore.QMetaObject.connectSlotsByName(form_splitting)

    def retranslateUi(self, form_splitting):
        _translate = QtCore.QCoreApplication.translate
        form_splitting.setWindowTitle(_translate("form_splitting", "Splitting"))
        self.pb_calculate.setText(_translate("form_splitting", "Calculate"))
        self.gb_input_data.setTitle(_translate("form_splitting", "Input data:"))
        self.lb_p_c2.setText(_translate("form_splitting", "P(C2):"))
        self.le_p_c1.setText(_translate("form_splitting", "0.25"))
        self.le_p_c1.setPlaceholderText(_translate("form_splitting", "0.25"))
        self.le_p_c2.setText(_translate("form_splitting", "0.75"))
        self.le_p_c2.setPlaceholderText(_translate("form_splitting", "0.75"))
        self.lb_p_c1.setText(_translate("form_splitting", "P(C1):"))
        self.gb_output_data.setTitle(_translate("form_splitting", "Output data:"))
        self.lb_false_alarm_probability.setText(_translate("form_splitting", "False alarm probability:"))
        self.lb_missing_error_detection_probability.setText(_translate("form_splitting", "Missing error detection probability:"))
        self.lb_total_error.setText(_translate("form_splitting", "Total error:"))
